// ================================================================
// REAL MA'LUMOT — salonning haqiqiy modellari
// ================================================================
//
// Bu fayl public/assets/ dagi rasm to'plamlaridan generatsiya qilingan.
// Kategoriya moslamasi — mockdata.categories.real.ts dagi PREFIX_MAP.
//
// TEKSHIRISH KERAK (generator standart qiymat qo'ygan):
//   name / description  — avtomatik nom, salon nomini qo'ying
//   narxlar             — kategoriya bo'yicha bir xil, har model uchun aniqlang
//   silhouette / fabrics / sizes — ko'ylaklarda standart qiymat
// ================================================================

import type { Accessory, Dress } from './helper.types.catalog';
import { photo, photoVariant, sizes } from './mockdata.helpers';

/** `true` — katalog faqat shu fayldagi real modellardan iborat bo'ladi */
export const USE_REAL_DATA = true;

// ================================================================
// KO'YLAKLAR (27 ta)
// ================================================================

export const REAL_DRESSES: Dress[] = [
  // ---------- w-sweetheart — вырез «сердечко» (4 model) ----------
  {
    id: 'd-w-sweetheart-1',
    slug: 'w-sweetheart-1',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-sweetheart',
    name: 'Аврора',
    description: 'Свадебное платье, вырез «сердечко». Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_800_000,
    salePrice: 5_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-sweetheart-1-ivory', 'Айвори', '#F5EFE6', [photo('w-sweetheart-1-1.jpg'), photo('w-sweetheart-1-2.jpg'), photo('w-sweetheart-1-3.jpg')])],
    defaultVariantId: 'd-w-sweetheart-1-ivory',
    isNew: true,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-23T10:00:00.000Z',
    updatedAt: '2026-08-23T10:00:00.000Z',
  },
  {
    id: 'd-w-sweetheart-2',
    slug: 'w-sweetheart-2',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-sweetheart',
    name: 'Белла',
    description: 'Свадебное платье, вырез «сердечко». Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_100_000,
    salePrice: 6_800_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-sweetheart-2-ivory', 'Айвори', '#F5EFE6', [photo('w-sweetheart-2-1.jpg'), photo('w-sweetheart-2-2.jpg'), photo('w-sweetheart-2-3.jpg')])],
    defaultVariantId: 'd-w-sweetheart-2-ivory',
    isNew: false,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-22T10:00:00.000Z',
    updatedAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'd-w-sweetheart-3',
    slug: 'w-sweetheart-3',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-sweetheart',
    name: 'Виктория',
    description: 'Свадебное платье, вырез «сердечко». Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_400_000,
    salePrice: 7_700_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-sweetheart-3-ivory', 'Айвори', '#F5EFE6', [photo('w-sweetheart-3-1.webp'), photo('w-sweetheart-3-2.jpg')])],
    defaultVariantId: 'd-w-sweetheart-3-ivory',
    isNew: false,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-21T10:00:00.000Z',
    updatedAt: '2026-08-21T10:00:00.000Z',
  },
  {
    id: 'd-w-sweetheart-4',
    slug: 'w-sweetheart-4',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-sweetheart',
    name: 'Грация',
    description: 'Свадебное платье, вырез «сердечко». Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_700_000,
    salePrice: 8_600_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-sweetheart-4-ivory', 'Айвори', '#F5EFE6', [photo('w-sweetheart-4-1.jpg'), photo('w-sweetheart-4-2.jpg'), photo('w-sweetheart-4-3.jpg')])],
    defaultVariantId: 'd-w-sweetheart-4-ivory',
    isNew: false,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
  },
  // ---------- w-vneek — V-образный вырез (2 model) ----------
  {
    id: 'd-w-vneek-1',
    slug: 'w-vneek-1',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-v-neck',
    name: 'Дольче',
    description: 'Свадебное платье, V-образный вырез. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_000_000,
    salePrice: 9_500_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'v-neck',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-vneek-1-ivory', 'Айвори', '#F5EFE6', [photo('w-vneek-1-1.jpg'), photo('w-vneek-1-2.jpg'), photo('w-vneek-1-3.jpg')])],
    defaultVariantId: 'd-w-vneek-1-ivory',
    isNew: true,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:00:00.000Z',
  },
  {
    id: 'd-w-vneek-2',
    slug: 'w-vneek-2',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-v-neck',
    name: 'Элиза',
    description: 'Свадебное платье, V-образный вырез. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_300_000,
    salePrice: 10_400_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'v-neck',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-vneek-2-ivory', 'Айвори', '#F5EFE6', [photo('w-vneek-2-1.webp'), photo('w-vneek-2-2.jpg'), photo('w-vneek-2-3.jpg')])],
    defaultVariantId: 'd-w-vneek-2-ivory',
    isNew: false,
    isFeatured: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
  },
  // ---------- w-square — квадратный вырез (3 model) ----------
  {
    id: 'd-w-square-1',
    slug: 'w-square-1',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-square',
    name: 'Жасмин',
    description: 'Свадебное платье, квадратный вырез. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_800_000,
    salePrice: 5_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'square',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-square-1-ivory', 'Айвори', '#F5EFE6', [photo('w-square-1-1.webp'), photo('w-square-1-2.jpg')])],
    defaultVariantId: 'd-w-square-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
  },
  {
    id: 'd-w-square-2',
    slug: 'w-square-2',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-square',
    name: 'Изабель',
    description: 'Свадебное платье, квадратный вырез. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_100_000,
    salePrice: 6_800_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'square',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-square-2-ivory', 'Айвори', '#F5EFE6', [photo('w-square-2-1.jpg'), photo('w-square-2-2.jpg'), photo('w-square-2-3.jpg')])],
    defaultVariantId: 'd-w-square-2-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
  },
  {
    id: 'd-w-square-3',
    slug: 'w-square-3',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-square',
    name: 'Камелия',
    description: 'Свадебное платье, квадратный вырез. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_400_000,
    salePrice: 7_700_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'square',
    sleeve: 'none',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-square-3-ivory', 'Айвори', '#F5EFE6', [photo('w-square-3-1.webp'), photo('w-square-3-2.jpg'), photo('w-square-3-3.jpg')])],
    defaultVariantId: 'd-w-square-3-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
  },
  // ---------- w-highneck — закрытый ворот (7 model) ----------
  {
    id: 'd-w-highneck-1',
    slug: 'w-highneck-1',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Лаура',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_700_000,
    salePrice: 8_600_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-1-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-1-1.jpg'), photo('w-highneck-1-2.jpg')])],
    defaultVariantId: 'd-w-highneck-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-2',
    slug: 'w-highneck-2',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Милана',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_000_000,
    salePrice: 9_500_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-2-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-2-1.jpg'), photo('w-highneck-2-2.jpg'), photo('w-highneck-2-3.jpg')])],
    defaultVariantId: 'd-w-highneck-2-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-13T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-3',
    slug: 'w-highneck-3',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Нора',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_300_000,
    salePrice: 10_400_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-3-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-3-1.jpg')])],
    defaultVariantId: 'd-w-highneck-3-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-4',
    slug: 'w-highneck-4',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Оливия',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_800_000,
    salePrice: 5_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-4-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-4-1.jpg'), photo('w-highneck-4-2.jpg'), photo('w-highneck-4-3.jpg')])],
    defaultVariantId: 'd-w-highneck-4-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-11T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-5',
    slug: 'w-highneck-5',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Патриция',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_100_000,
    salePrice: 6_800_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-5-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-5-1.jpeg'), photo('w-highneck-5-2.jpg')])],
    defaultVariantId: 'd-w-highneck-5-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-6',
    slug: 'w-highneck-6',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'Роксана',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_400_000,
    salePrice: 7_700_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-6-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-6-1.webp'), photo('w-highneck-6-2.jpg')])],
    defaultVariantId: 'd-w-highneck-6-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-09T10:00:00.000Z',
    updatedAt: '2026-08-09T10:00:00.000Z',
  },
  {
    id: 'd-w-highneck-7',
    slug: 'w-highneck-7',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-high-neck',
    name: 'София',
    description: 'Свадебное платье, закрытый ворот. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_700_000,
    salePrice: 8_600_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-highneck-7-ivory', 'Айвори', '#F5EFE6', [photo('w-highneck-7-1.webp'), photo('w-highneck-7-2.jpg')])],
    defaultVariantId: 'd-w-highneck-7-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-08T10:00:00.000Z',
  },
  // ---------- w-onesh — асимметричный верх на одно плечо (5 model) ----------
  {
    id: 'd-w-onesh-1',
    slug: 'w-onesh-1',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-one-shoulder',
    name: 'Тиффани',
    description: 'Свадебное платье, асимметричный верх на одно плечо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_000_000,
    salePrice: 9_500_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'one-shoulder',
    sleeve: 'strap',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-onesh-1-ivory', 'Айвори', '#F5EFE6', [photo('w-onesh-1-1.jpg'), photo('w-onesh-1-2.jpg')])],
    defaultVariantId: 'd-w-onesh-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-07T10:00:00.000Z',
    updatedAt: '2026-08-07T10:00:00.000Z',
  },
  {
    id: 'd-w-onesh-2',
    slug: 'w-onesh-2',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-one-shoulder',
    name: 'Ульяна',
    description: 'Свадебное платье, асимметричный верх на одно плечо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_300_000,
    salePrice: 10_400_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'one-shoulder',
    sleeve: 'strap',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-onesh-2-ivory', 'Айвори', '#F5EFE6', [photo('w-onesh-2-1.jpg'), photo('w-onesh-2-2.jpg'), photo('w-onesh-2-3.jpg')])],
    defaultVariantId: 'd-w-onesh-2-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-06T10:00:00.000Z',
    updatedAt: '2026-08-06T10:00:00.000Z',
  },
  {
    id: 'd-w-onesh-3',
    slug: 'w-onesh-3',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-one-shoulder',
    name: 'Флора',
    description: 'Свадебное платье, асимметричный верх на одно плечо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_800_000,
    salePrice: 5_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'one-shoulder',
    sleeve: 'strap',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-onesh-3-ivory', 'Айвори', '#F5EFE6', [photo('w-onesh-3-1.jpg')])],
    defaultVariantId: 'd-w-onesh-3-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: '2026-08-05T10:00:00.000Z',
  },
  {
    id: 'd-w-onesh-4',
    slug: 'w-onesh-4',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-one-shoulder',
    name: 'Хлоя',
    description: 'Свадебное платье, асимметричный верх на одно плечо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_100_000,
    salePrice: 6_800_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'one-shoulder',
    sleeve: 'strap',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-onesh-4-ivory', 'Айвори', '#F5EFE6', [photo('w-onesh-4-1.jpg'), photo('w-onesh-4-2.jpg'), photo('w-onesh-4-3.jpg')])],
    defaultVariantId: 'd-w-onesh-4-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-04T10:00:00.000Z',
    updatedAt: '2026-08-04T10:00:00.000Z',
  },
  {
    id: 'd-w-onesh-5',
    slug: 'w-onesh-5',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-one-shoulder',
    name: 'Церера',
    description: 'Свадебное платье, асимметричный верх на одно плечо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_400_000,
    salePrice: 7_700_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'one-shoulder',
    sleeve: 'strap',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-onesh-5-ivory', 'Айвори', '#F5EFE6', [photo('w-onesh-5-1.avif'), photo('w-onesh-5-2.jpg'), photo('w-onesh-5-3.jpg')])],
    defaultVariantId: 'd-w-onesh-5-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-03T10:00:00.000Z',
    updatedAt: '2026-08-03T10:00:00.000Z',
  },
  // ---------- w-hj-barg — закрытый крой с накидкой (2 model) ----------
  {
    id: 'd-w-hj-barg-1',
    slug: 'w-hj-barg-1',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-cape',
    name: 'Челси',
    description: 'Свадебное платье, закрытый крой с накидкой. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_700_000,
    salePrice: 8_600_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-barg-1-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-barg-1-1.jpg'), photo('w-hj-barg-1-2.jpg')])],
    defaultVariantId: 'd-w-hj-barg-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-02T10:00:00.000Z',
    updatedAt: '2026-08-02T10:00:00.000Z',
  },
  {
    id: 'd-w-hj-barg-2',
    slug: 'w-hj-barg-2',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-cape',
    name: 'Шанель',
    description: 'Свадебное платье, закрытый крой с накидкой. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_000_000,
    salePrice: 9_500_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-barg-2-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-barg-2-1.jpg'), photo('w-hj-barg-2-2.jpg'), photo('w-hj-barg-2-3.jpg')])],
    defaultVariantId: 'd-w-hj-barg-2-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  // ---------- w-hj-palto — закрытый крой с длинной накидкой-пальто (3 model) ----------
  {
    id: 'd-w-hj-palto-1',
    slug: 'w-hj-palto-1',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-coat',
    name: 'Эмилия',
    description: 'Свадебное платье, закрытый крой с длинной накидкой-пальто. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 3_300_000,
    salePrice: 10_400_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-palto-1-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-palto-1-1.jpg'), photo('w-hj-palto-1-2.jpg')])],
    defaultVariantId: 'd-w-hj-palto-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-31T10:00:00.000Z',
    updatedAt: '2026-07-31T10:00:00.000Z',
  },
  {
    id: 'd-w-hj-palto-2',
    slug: 'w-hj-palto-2',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-coat',
    name: 'Юнона',
    description: 'Свадебное платье, закрытый крой с длинной накидкой-пальто. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_800_000,
    salePrice: 5_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-palto-2-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-palto-2-1.jpg')])],
    defaultVariantId: 'd-w-hj-palto-2-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-30T10:00:00.000Z',
    updatedAt: '2026-07-30T10:00:00.000Z',
  },
  {
    id: 'd-w-hj-palto-3',
    slug: 'w-hj-palto-3',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-coat',
    name: 'Ясмин',
    description: 'Свадебное платье, закрытый крой с длинной накидкой-пальто. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_100_000,
    salePrice: 6_800_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-palto-3-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-palto-3-1.jpg')])],
    defaultVariantId: 'd-w-hj-palto-3-ivory',
    isNew: false,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-29T10:00:00.000Z',
    updatedAt: '2026-07-29T10:00:00.000Z',
  },
  // ---------- w-hj-china — закрытый крой с воротником-стойкой (1 model) ----------
  {
    id: 'd-w-hj-china-1',
    slug: 'w-hj-china-1',
    kind: 'dress',
    categoryId: 'hijab',
    subcategoryId: 'hijab-stand-collar',
    name: 'Ариана',
    description: 'Свадебное платье, закрытый крой с воротником-стойкой. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_400_000,
    salePrice: 7_700_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48], [50]),
    variants: [photoVariant('d-w-hj-china-1-ivory', 'Айвори', '#F5EFE6', [photo('w-hj-china-1-1.jpg'), photo('w-hj-china-1-2.jpg')])],
    defaultVariantId: 'd-w-hj-china-1-ivory',
    isNew: true,
    isFeatured: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-28T10:00:00.000Z',
    updatedAt: '2026-07-28T10:00:00.000Z',
  },
];

// ================================================================
// AKSESSUARLAR (64 ta)
// ================================================================

export const REAL_ACCESSORIES: Accessory[] = [
  // ---------- shoes-classic — классические свадебные лодочки (2 model) ----------
  {
    id: 'a-shoes-classic-1',
    slug: 'shoes-classic-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-classic',
    accessoryType: 'shoes',
    name: 'Туфли-лодочки 01',
    description: 'Свадебная обувь, классические свадебные лодочки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-1-white', 'Белый', '#FFFFFF', [photo('shoes-classic-1-1.jpg'), photo('shoes-classic-1-2.jpg')])],
    defaultVariantId: 'a-shoes-classic-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-23T10:00:00.000Z',
    updatedAt: '2026-08-23T10:00:00.000Z',
  },
  {
    id: 'a-shoes-classic-2',
    slug: 'shoes-classic-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-classic',
    accessoryType: 'shoes',
    name: 'Туфли-лодочки 02',
    description: 'Свадебная обувь, классические свадебные лодочки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-2-white', 'Белый', '#FFFFFF', [photo('shoes-classic-2-1.jpg'), photo('shoes-classic-2-2.jpg')])],
    defaultVariantId: 'a-shoes-classic-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-22T10:00:00.000Z',
    updatedAt: '2026-08-22T10:00:00.000Z',
  },
  // ---------- shoes-classic-gul — лодочки с цветочным декором (4 model) ----------
  {
    id: 'a-shoes-classic-gul-1',
    slug: 'shoes-classic-gul-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-flower',
    accessoryType: 'shoes',
    name: 'Туфли с цветами 01',
    description: 'Свадебная обувь, лодочки с цветочным декором. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-gul-1-white', 'Белый', '#FFFFFF', [photo('shoes-classic-gul-1-1.jpg')])],
    defaultVariantId: 'a-shoes-classic-gul-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-21T10:00:00.000Z',
    updatedAt: '2026-08-21T10:00:00.000Z',
  },
  {
    id: 'a-shoes-classic-gul-2',
    slug: 'shoes-classic-gul-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-flower',
    accessoryType: 'shoes',
    name: 'Туфли с цветами 02',
    description: 'Свадебная обувь, лодочки с цветочным декором. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-gul-2-white', 'Белый', '#FFFFFF', [photo('shoes-classic-gul-2-1.jpg'), photo('shoes-classic-gul-2-2.jpg')])],
    defaultVariantId: 'a-shoes-classic-gul-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'a-shoes-classic-gul-3',
    slug: 'shoes-classic-gul-3',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-flower',
    accessoryType: 'shoes',
    name: 'Туфли с цветами 03',
    description: 'Свадебная обувь, лодочки с цветочным декором. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-gul-3-white', 'Белый', '#FFFFFF', [photo('shoes-classic-gul-3-1.jpg')])],
    defaultVariantId: 'a-shoes-classic-gul-3-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:00:00.000Z',
  },
  {
    id: 'a-shoes-classic-gul-4',
    slug: 'shoes-classic-gul-4',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-flower',
    accessoryType: 'shoes',
    name: 'Туфли с цветами 04',
    description: 'Свадебная обувь, лодочки с цветочным декором. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-classic-gul-4-white', 'Белый', '#FFFFFF', [photo('shoes-classic-gul-4-1.jpg')])],
    defaultVariantId: 'a-shoes-classic-gul-4-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
  },
  // ---------- shoes-crystall — лодочки с кристаллами (4 model) ----------
  {
    id: 'a-shoes-crystall-1',
    slug: 'shoes-crystall-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-crystal',
    accessoryType: 'shoes',
    name: 'Туфли с кристаллами 01',
    description: 'Свадебная обувь, лодочки с кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-crystall-1-white', 'Белый', '#FFFFFF', [photo('shoes-crystall-1-1.jpg')])],
    defaultVariantId: 'a-shoes-crystall-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
  },
  {
    id: 'a-shoes-crystall-2',
    slug: 'shoes-crystall-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-crystal',
    accessoryType: 'shoes',
    name: 'Туфли с кристаллами 02',
    description: 'Свадебная обувь, лодочки с кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-crystall-2-white', 'Белый', '#FFFFFF', [photo('shoes-crystall-2-1.jpg')])],
    defaultVariantId: 'a-shoes-crystall-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
  },
  {
    id: 'a-shoes-crystall-3',
    slug: 'shoes-crystall-3',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-crystal',
    accessoryType: 'shoes',
    name: 'Туфли с кристаллами 03',
    description: 'Свадебная обувь, лодочки с кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-crystall-3-white', 'Белый', '#FFFFFF', [photo('shoes-crystall-3-1.jpg')])],
    defaultVariantId: 'a-shoes-crystall-3-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'a-shoes-crystall-4',
    slug: 'shoes-crystall-4',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-crystal',
    accessoryType: 'shoes',
    name: 'Туфли с кристаллами 04',
    description: 'Свадебная обувь, лодочки с кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-crystall-4-white', 'Белый', '#FFFFFF', [photo('shoes-crystall-4-1.jpg')])],
    defaultVariantId: 'a-shoes-crystall-4-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
  },
  // ---------- shoes-block-hell — устойчивый широкий каблук (4 model) ----------
  {
    id: 'a-shoes-block-hell-1',
    slug: 'shoes-block-hell-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-block-heel',
    accessoryType: 'shoes',
    name: 'Туфли на устойчивом каблуке 01',
    description: 'Свадебная обувь, устойчивый широкий каблук. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-block-hell-1-white', 'Белый', '#FFFFFF', [photo('shoes-block-hell-1-1.jpg')])],
    defaultVariantId: 'a-shoes-block-hell-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-13T10:00:00.000Z',
  },
  {
    id: 'a-shoes-block-hell-2',
    slug: 'shoes-block-hell-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-block-heel',
    accessoryType: 'shoes',
    name: 'Туфли на устойчивом каблуке 02',
    description: 'Свадебная обувь, устойчивый широкий каблук. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-block-hell-2-white', 'Белый', '#FFFFFF', [photo('shoes-block-hell-2-1.jpg')])],
    defaultVariantId: 'a-shoes-block-hell-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
  },
  {
    id: 'a-shoes-block-hell-3',
    slug: 'shoes-block-hell-3',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-block-heel',
    accessoryType: 'shoes',
    name: 'Туфли на устойчивом каблуке 03',
    description: 'Свадебная обувь, устойчивый широкий каблук. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-block-hell-3-white', 'Белый', '#FFFFFF', [photo('shoes-block-hell-3-1.jpg')])],
    defaultVariantId: 'a-shoes-block-hell-3-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-11T10:00:00.000Z',
  },
  {
    id: 'a-shoes-block-hell-4',
    slug: 'shoes-block-hell-4',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-block-heel',
    accessoryType: 'shoes',
    name: 'Туфли на устойчивом каблуке 04',
    description: 'Свадебная обувь, устойчивый широкий каблук. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-block-hell-4-white', 'Белый', '#FFFFFF', [photo('shoes-block-hell-4-1.jpg')])],
    defaultVariantId: 'a-shoes-block-hell-4-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-08-10T10:00:00.000Z',
  },
  // ---------- shoes-kitten-hell — низкий каблук kitten heel (3 model) ----------
  {
    id: 'a-shoes-kitten-hell-1',
    slug: 'shoes-kitten-hell-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-kitten-heel',
    accessoryType: 'shoes',
    name: 'Туфли на низком каблуке 01',
    description: 'Свадебная обувь, низкий каблук kitten heel. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-kitten-hell-1-white', 'Белый', '#FFFFFF', [photo('shoes-kitten-hell-1-1.jpg')])],
    defaultVariantId: 'a-shoes-kitten-hell-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-09T10:00:00.000Z',
    updatedAt: '2026-08-09T10:00:00.000Z',
  },
  {
    id: 'a-shoes-kitten-hell-2',
    slug: 'shoes-kitten-hell-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-kitten-heel',
    accessoryType: 'shoes',
    name: 'Туфли на низком каблуке 02',
    description: 'Свадебная обувь, низкий каблук kitten heel. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-kitten-hell-2-white', 'Белый', '#FFFFFF', [photo('shoes-kitten-hell-2-1.jpg')])],
    defaultVariantId: 'a-shoes-kitten-hell-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-08T10:00:00.000Z',
  },
  {
    id: 'a-shoes-kitten-hell-3',
    slug: 'shoes-kitten-hell-3',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-kitten-heel',
    accessoryType: 'shoes',
    name: 'Туфли на низком каблуке 03',
    description: 'Свадебная обувь, низкий каблук kitten heel. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-kitten-hell-3-white', 'Белый', '#FFFFFF', [photo('shoes-kittent-hell-3-1.jpg')])],
    defaultVariantId: 'a-shoes-kitten-hell-3-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-07T10:00:00.000Z',
    updatedAt: '2026-08-07T10:00:00.000Z',
  },
  // ---------- shoes-strapy — босоножки на тонких ремешках (4 model) ----------
  {
    id: 'a-shoes-strapy-1',
    slug: 'shoes-strapy-1',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-strappy',
    accessoryType: 'shoes',
    name: 'Босоножки 01',
    description: 'Свадебная обувь, босоножки на тонких ремешках. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-strapy-1-white', 'Белый', '#FFFFFF', [photo('shoes-strapy-1-1.jpg')])],
    defaultVariantId: 'a-shoes-strapy-1-white',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-06T10:00:00.000Z',
    updatedAt: '2026-08-06T10:00:00.000Z',
  },
  {
    id: 'a-shoes-strapy-2',
    slug: 'shoes-strapy-2',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-strappy',
    accessoryType: 'shoes',
    name: 'Босоножки 02',
    description: 'Свадебная обувь, босоножки на тонких ремешках. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-strapy-2-white', 'Белый', '#FFFFFF', [photo('shoes-strapy-2-1.jpg')])],
    defaultVariantId: 'a-shoes-strapy-2-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: '2026-08-05T10:00:00.000Z',
  },
  {
    id: 'a-shoes-strapy-3',
    slug: 'shoes-strapy-3',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-strappy',
    accessoryType: 'shoes',
    name: 'Босоножки 03',
    description: 'Свадебная обувь, босоножки на тонких ремешках. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-strapy-3-white', 'Белый', '#FFFFFF', [photo('shoes-strapy-3-1.jpg')])],
    defaultVariantId: 'a-shoes-strapy-3-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-04T10:00:00.000Z',
    updatedAt: '2026-08-04T10:00:00.000Z',
  },
  {
    id: 'a-shoes-strapy-4',
    slug: 'shoes-strapy-4',
    kind: 'accessory',
    categoryId: 'shoes',
    subcategoryId: 'shoes-strappy',
    accessoryType: 'shoes',
    name: 'Босоножки 04',
    description: 'Свадебная обувь, босоножки на тонких ремешках. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 250_000,
    salePrice: 900_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Экокожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: [photoVariant('a-shoes-strapy-4-white', 'Белый', '#FFFFFF', [photo('shoes-strapy-4-1.jpg')])],
    defaultVariantId: 'a-shoes-strapy-4-white',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-03T10:00:00.000Z',
    updatedAt: '2026-08-03T10:00:00.000Z',
  },
  // ---------- fata — свадебная фата из мягкого фатина (6 dona) ----------
  {
    id: 'a-fata-1',
    slug: 'fata-1',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 01',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-1-main', 'Айвори', '#F5EFE6', [photo('fata-1.jpg')])],
    defaultVariantId: 'a-fata-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-02T10:00:00.000Z',
    updatedAt: '2026-08-02T10:00:00.000Z',
  },
  {
    id: 'a-fata-2',
    slug: 'fata-2',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 02',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-2-main', 'Айвори', '#F5EFE6', [photo('fata-2.jpg')])],
    defaultVariantId: 'a-fata-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'a-fata-3',
    slug: 'fata-3',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 03',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-3-main', 'Айвори', '#F5EFE6', [photo('fata-3.jpg')])],
    defaultVariantId: 'a-fata-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-31T10:00:00.000Z',
    updatedAt: '2026-07-31T10:00:00.000Z',
  },
  {
    id: 'a-fata-4',
    slug: 'fata-4',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 04',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-4-main', 'Айвори', '#F5EFE6', [photo('fata-4.jpg')])],
    defaultVariantId: 'a-fata-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-30T10:00:00.000Z',
    updatedAt: '2026-07-30T10:00:00.000Z',
  },
  {
    id: 'a-fata-5',
    slug: 'fata-5',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 05',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-5-main', 'Айвори', '#F5EFE6', [photo('fata-5.jpg')])],
    defaultVariantId: 'a-fata-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-29T10:00:00.000Z',
    updatedAt: '2026-07-29T10:00:00.000Z',
  },
  {
    id: 'a-fata-6',
    slug: 'fata-6',
    kind: 'accessory',
    categoryId: 'veils',
    accessoryType: 'veil',
    name: 'Фата 06',
    description: 'Свадебная фата из мягкого фатина. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 200_000,
    salePrice: 700_000,
    deposit: 140_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: [photoVariant('a-fata-6-main', 'Айвори', '#F5EFE6', [photo('fata-6.jpg')])],
    defaultVariantId: 'a-fata-6-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-28T10:00:00.000Z',
    updatedAt: '2026-07-28T10:00:00.000Z',
  },
  // ---------- tish — заколка-гребень с жемчугом и кристаллами (7 dona) ----------
  {
    id: 'a-tish-1',
    slug: 'tish-1',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 01',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-1-main', 'Серебро', '#C0C0C0', [photo('tish-1.jpg')])],
    defaultVariantId: 'a-tish-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-27T10:00:00.000Z',
    updatedAt: '2026-07-27T10:00:00.000Z',
  },
  {
    id: 'a-tish-2',
    slug: 'tish-2',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 02',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-2-main', 'Серебро', '#C0C0C0', [photo('tish-2.webp')])],
    defaultVariantId: 'a-tish-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-26T10:00:00.000Z',
    updatedAt: '2026-07-26T10:00:00.000Z',
  },
  {
    id: 'a-tish-3',
    slug: 'tish-3',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 03',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-3-main', 'Серебро', '#C0C0C0', [photo('tish-3.jpg')])],
    defaultVariantId: 'a-tish-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-25T10:00:00.000Z',
    updatedAt: '2026-07-25T10:00:00.000Z',
  },
  {
    id: 'a-tish-4',
    slug: 'tish-4',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 04',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-4-main', 'Серебро', '#C0C0C0', [photo('tish-4.jpg')])],
    defaultVariantId: 'a-tish-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-24T10:00:00.000Z',
    updatedAt: '2026-07-24T10:00:00.000Z',
  },
  {
    id: 'a-tish-5',
    slug: 'tish-5',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 05',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-5-main', 'Серебро', '#C0C0C0', [photo('tish-5.jpg')])],
    defaultVariantId: 'a-tish-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-23T10:00:00.000Z',
    updatedAt: '2026-07-23T10:00:00.000Z',
  },
  {
    id: 'a-tish-6',
    slug: 'tish-6',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 06',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-6-main', 'Серебро', '#C0C0C0', [photo('tish-6.jpg')])],
    defaultVariantId: 'a-tish-6-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-22T10:00:00.000Z',
    updatedAt: '2026-07-22T10:00:00.000Z',
  },
  {
    id: 'a-tish-7',
    slug: 'tish-7',
    kind: 'accessory',
    categoryId: 'hairpins',
    accessoryType: 'hairpin',
    name: 'Заколка 07',
    description: 'Заколка-гребень с жемчугом и кристаллами. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 350_000,
    deposit: 70_000,
    currency: 'UZS',
    material: 'Металл, жемчуг',
    oneSize: true,
    variants: [photoVariant('a-tish-7-main', 'Серебро', '#C0C0C0', [photo('tish-7.jpg')])],
    defaultVariantId: 'a-tish-7-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-21T10:00:00.000Z',
    updatedAt: '2026-07-21T10:00:00.000Z',
  },
  // ---------- toj — корона-ободок для причёски невесты (7 dona) ----------
  {
    id: 'a-toj-1',
    slug: 'toj-1',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 01',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-1-main', 'Серебро', '#C0C0C0', [photo('toj-1.jpg')])],
    defaultVariantId: 'a-toj-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-20T10:00:00.000Z',
    updatedAt: '2026-07-20T10:00:00.000Z',
  },
  {
    id: 'a-toj-2',
    slug: 'toj-2',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 02',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-2-main', 'Серебро', '#C0C0C0', [photo('toj-2.jpg')])],
    defaultVariantId: 'a-toj-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-19T10:00:00.000Z',
    updatedAt: '2026-07-19T10:00:00.000Z',
  },
  {
    id: 'a-toj-3',
    slug: 'toj-3',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 03',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-3-main', 'Серебро', '#C0C0C0', [photo('toj-3.jpg')])],
    defaultVariantId: 'a-toj-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-18T10:00:00.000Z',
    updatedAt: '2026-07-18T10:00:00.000Z',
  },
  {
    id: 'a-toj-4',
    slug: 'toj-4',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 04',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-4-main', 'Серебро', '#C0C0C0', [photo('toj-4.jpg')])],
    defaultVariantId: 'a-toj-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-17T10:00:00.000Z',
    updatedAt: '2026-07-17T10:00:00.000Z',
  },
  {
    id: 'a-toj-5',
    slug: 'toj-5',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 05',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-5-main', 'Серебро', '#C0C0C0', [photo('toj-6.jpg')])],
    defaultVariantId: 'a-toj-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-16T10:00:00.000Z',
    updatedAt: '2026-07-16T10:00:00.000Z',
  },
  {
    id: 'a-toj-6',
    slug: 'toj-6',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 06',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-6-main', 'Серебро', '#C0C0C0', [photo('toj-7.jpg')])],
    defaultVariantId: 'a-toj-6-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-15T10:00:00.000Z',
    updatedAt: '2026-07-15T10:00:00.000Z',
  },
  {
    id: 'a-toj-7',
    slug: 'toj-7',
    kind: 'accessory',
    categoryId: 'tiaras',
    accessoryType: 'tiara',
    name: 'Корона 07',
    description: 'Корона-ободок для причёски невесты. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 600_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-toj-7-main', 'Серебро', '#C0C0C0', [photo('toj-8.jpg')])],
    defaultVariantId: 'a-toj-7-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-14T10:00:00.000Z',
    updatedAt: '2026-07-14T10:00:00.000Z',
  },
  // ---------- nabor — комплект: колье, серьги, браслет и кольцо (5 dona) ----------
  {
    id: 'a-nabor-1',
    slug: 'nabor-1',
    kind: 'accessory',
    categoryId: 'jewelry',
    accessoryType: 'jewelry',
    name: 'Набор украшений 01',
    description: 'Комплект: колье, серьги, браслет и кольцо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 400_000,
    salePrice: 1_500_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Металл, фианиты',
    oneSize: true,
    variants: [photoVariant('a-nabor-1-main', 'Серебро', '#C0C0C0', [photo('nabor-1.jpg')])],
    defaultVariantId: 'a-nabor-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-13T10:00:00.000Z',
    updatedAt: '2026-07-13T10:00:00.000Z',
  },
  {
    id: 'a-nabor-2',
    slug: 'nabor-2',
    kind: 'accessory',
    categoryId: 'jewelry',
    accessoryType: 'jewelry',
    name: 'Набор украшений 02',
    description: 'Комплект: колье, серьги, браслет и кольцо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 400_000,
    salePrice: 1_500_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Металл, фианиты',
    oneSize: true,
    variants: [photoVariant('a-nabor-2-main', 'Серебро', '#C0C0C0', [photo('nabor-2.jpg')])],
    defaultVariantId: 'a-nabor-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-12T10:00:00.000Z',
    updatedAt: '2026-07-12T10:00:00.000Z',
  },
  {
    id: 'a-nabor-3',
    slug: 'nabor-3',
    kind: 'accessory',
    categoryId: 'jewelry',
    accessoryType: 'jewelry',
    name: 'Набор украшений 03',
    description: 'Комплект: колье, серьги, браслет и кольцо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 400_000,
    salePrice: 1_500_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Металл, фианиты',
    oneSize: true,
    variants: [photoVariant('a-nabor-3-main', 'Серебро', '#C0C0C0', [photo('nabor-3.jpg')])],
    defaultVariantId: 'a-nabor-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-11T10:00:00.000Z',
    updatedAt: '2026-07-11T10:00:00.000Z',
  },
  {
    id: 'a-nabor-4',
    slug: 'nabor-4',
    kind: 'accessory',
    categoryId: 'jewelry',
    accessoryType: 'jewelry',
    name: 'Набор украшений 04',
    description: 'Комплект: колье, серьги, браслет и кольцо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 400_000,
    salePrice: 1_500_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Металл, фианиты',
    oneSize: true,
    variants: [photoVariant('a-nabor-4-main', 'Серебро', '#C0C0C0', [photo('nabor-4.jpg')])],
    defaultVariantId: 'a-nabor-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-10T10:00:00.000Z',
    updatedAt: '2026-07-10T10:00:00.000Z',
  },
  {
    id: 'a-nabor-5',
    slug: 'nabor-5',
    kind: 'accessory',
    categoryId: 'jewelry',
    accessoryType: 'jewelry',
    name: 'Набор украшений 05',
    description: 'Комплект: колье, серьги, браслет и кольцо. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 400_000,
    salePrice: 1_500_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Металл, фианиты',
    oneSize: true,
    variants: [photoVariant('a-nabor-5-main', 'Серебро', '#C0C0C0', [photo('nabor-5.jpg')])],
    defaultVariantId: 'a-nabor-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-09T10:00:00.000Z',
    updatedAt: '2026-07-09T10:00:00.000Z',
  },
  // ---------- setka — вуалетка с сеткой для лица (6 dona) ----------
  {
    id: 'a-setka-1',
    slug: 'setka-1',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 01',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-1-main', 'Айвори', '#F5EFE6', [photo('setka-1.jpg')])],
    defaultVariantId: 'a-setka-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-08T10:00:00.000Z',
    updatedAt: '2026-07-08T10:00:00.000Z',
  },
  {
    id: 'a-setka-2',
    slug: 'setka-2',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 02',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-2-main', 'Айвори', '#F5EFE6', [photo('setka-2.jpg')])],
    defaultVariantId: 'a-setka-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-07T10:00:00.000Z',
    updatedAt: '2026-07-07T10:00:00.000Z',
  },
  {
    id: 'a-setka-3',
    slug: 'setka-3',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 03',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-3-main', 'Айвори', '#F5EFE6', [photo('setka-3.jpg')])],
    defaultVariantId: 'a-setka-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-06T10:00:00.000Z',
    updatedAt: '2026-07-06T10:00:00.000Z',
  },
  {
    id: 'a-setka-4',
    slug: 'setka-4',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 04',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-4-main', 'Айвори', '#F5EFE6', [photo('setka-4.jpg')])],
    defaultVariantId: 'a-setka-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-05T10:00:00.000Z',
    updatedAt: '2026-07-05T10:00:00.000Z',
  },
  {
    id: 'a-setka-5',
    slug: 'setka-5',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 05',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-5-main', 'Айвори', '#F5EFE6', [photo('setka-5.jpg')])],
    defaultVariantId: 'a-setka-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
  },
  {
    id: 'a-setka-6',
    slug: 'setka-6',
    kind: 'accessory',
    categoryId: 'face-veils',
    accessoryType: 'face-veil',
    name: 'Вуалетка 06',
    description: 'Вуалетка с сеткой для лица. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 500_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Сетка, текстиль',
    oneSize: true,
    variants: [photoVariant('a-setka-6-main', 'Айвори', '#F5EFE6', [photo('setka-6.webp')])],
    defaultVariantId: 'a-setka-6-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-03T10:00:00.000Z',
    updatedAt: '2026-07-03T10:00:00.000Z',
  },
  // ---------- per — ажурные свадебные перчатки (5 dona) ----------
  {
    id: 'a-per-1',
    slug: 'per-1',
    kind: 'accessory',
    categoryId: 'gloves',
    accessoryType: 'gloves',
    name: 'Перчатки 01',
    description: 'Ажурные свадебные перчатки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 300_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Кружево, сетка',
    oneSize: true,
    variants: [photoVariant('a-per-1-main', 'Белый', '#FFFFFF', [photo('per-1.jpg')])],
    defaultVariantId: 'a-per-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-02T10:00:00.000Z',
    updatedAt: '2026-07-02T10:00:00.000Z',
  },
  {
    id: 'a-per-2',
    slug: 'per-2',
    kind: 'accessory',
    categoryId: 'gloves',
    accessoryType: 'gloves',
    name: 'Перчатки 02',
    description: 'Ажурные свадебные перчатки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 300_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Кружево, сетка',
    oneSize: true,
    variants: [photoVariant('a-per-2-main', 'Белый', '#FFFFFF', [photo('per-2.jpg')])],
    defaultVariantId: 'a-per-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-07-01T10:00:00.000Z',
    updatedAt: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'a-per-3',
    slug: 'per-3',
    kind: 'accessory',
    categoryId: 'gloves',
    accessoryType: 'gloves',
    name: 'Перчатки 03',
    description: 'Ажурные свадебные перчатки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 300_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Кружево, сетка',
    oneSize: true,
    variants: [photoVariant('a-per-3-main', 'Белый', '#FFFFFF', [photo('per-3.jpg')])],
    defaultVariantId: 'a-per-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
  },
  {
    id: 'a-per-4',
    slug: 'per-4',
    kind: 'accessory',
    categoryId: 'gloves',
    accessoryType: 'gloves',
    name: 'Перчатки 04',
    description: 'Ажурные свадебные перчатки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 300_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Кружево, сетка',
    oneSize: true,
    variants: [photoVariant('a-per-4-main', 'Белый', '#FFFFFF', [photo('per-4.jpg')])],
    defaultVariantId: 'a-per-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-29T10:00:00.000Z',
    updatedAt: '2026-06-29T10:00:00.000Z',
  },
  {
    id: 'a-per-5',
    slug: 'per-5',
    kind: 'accessory',
    categoryId: 'gloves',
    accessoryType: 'gloves',
    name: 'Перчатки 05',
    description: 'Ажурные свадебные перчатки. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 100_000,
    salePrice: 300_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Кружево, сетка',
    oneSize: true,
    variants: [photoVariant('a-per-5-main', 'Белый', '#FFFFFF', [photo('per-5.jpg')])],
    defaultVariantId: 'a-per-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-28T10:00:00.000Z',
    updatedAt: '2026-06-28T10:00:00.000Z',
  },
  // ---------- hand — браслет-слейв с кольцом (7 dona) ----------
  {
    id: 'a-hand-1',
    slug: 'hand-1',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 01',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-1-main', 'Золото', '#D4AF37', [photo('hand-1.jpg')])],
    defaultVariantId: 'a-hand-1-main',
    isNew: true,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-27T10:00:00.000Z',
    updatedAt: '2026-06-27T10:00:00.000Z',
  },
  {
    id: 'a-hand-2',
    slug: 'hand-2',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 02',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-2-main', 'Золото', '#D4AF37', [photo('hand-2.jpg')])],
    defaultVariantId: 'a-hand-2-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-26T10:00:00.000Z',
    updatedAt: '2026-06-26T10:00:00.000Z',
  },
  {
    id: 'a-hand-3',
    slug: 'hand-3',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 03',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-3-main', 'Золото', '#D4AF37', [photo('hand-3.jpg')])],
    defaultVariantId: 'a-hand-3-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-25T10:00:00.000Z',
    updatedAt: '2026-06-25T10:00:00.000Z',
  },
  {
    id: 'a-hand-4',
    slug: 'hand-4',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 04',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-4-main', 'Золото', '#D4AF37', [photo('hand-4.jpg')])],
    defaultVariantId: 'a-hand-4-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-24T10:00:00.000Z',
    updatedAt: '2026-06-24T10:00:00.000Z',
  },
  {
    id: 'a-hand-5',
    slug: 'hand-5',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 05',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-5-main', 'Золото', '#D4AF37', [photo('hand-5.jpg')])],
    defaultVariantId: 'a-hand-5-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-23T10:00:00.000Z',
    updatedAt: '2026-06-23T10:00:00.000Z',
  },
  {
    id: 'a-hand-6',
    slug: 'hand-6',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 06',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-6-main', 'Золото', '#D4AF37', [photo('hand-6.jpeg')])],
    defaultVariantId: 'a-hand-6-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-22T10:00:00.000Z',
    updatedAt: '2026-06-22T10:00:00.000Z',
  },
  {
    id: 'a-hand-7',
    slug: 'hand-7',
    kind: 'accessory',
    categoryId: 'bracelets',
    accessoryType: 'bracelet',
    name: 'Браслет на руку 07',
    description: 'Браслет-слейв с кольцом. Точное описание уточните в салоне.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 450_000,
    deposit: 90_000,
    currency: 'UZS',
    material: 'Металл, кристаллы',
    oneSize: true,
    variants: [photoVariant('a-hand-7-main', 'Золото', '#D4AF37', [photo('hand-6.jpg')])],
    defaultVariantId: 'a-hand-7-main',
    isNew: false,
    isAvailable: true,
    bookedDates: [],
    createdAt: '2026-06-21T10:00:00.000Z',
    updatedAt: '2026-06-21T10:00:00.000Z',
  },
];
