import type { Accessory } from './helper.types.catalog';
import { daysFromNow, seedVariants } from './mockdata.helpers';

const NOW = '2026-01-15T10:00:00.000Z';

export const MOCK_ACCESSORIES: Accessory[] = [
  {
    id: 'a-veil-classic',
    slug: 'veil-classic',
    sku: 'AC-001',
    kind: 'accessory',
    categoryId: 'veils',
    subcategoryId: 'veils-long',
    accessoryType: 'veil',
    tags: ['фата', 'длинная'],
    name: 'Фата «Классик» 2 м',
    description: 'Двухслойная фата из мягкого фатина с обработанным краем. Крепится на гребень.',
    careInstructions: 'Ручная стирка в холодной воде, сушить в расправленном виде.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 180_000,
    salePrice: 650_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Фатин',
    oneSize: true,
    variants: seedVariants('a-veil-classic', 'veil-classic-ivory', 2),
    defaultVariantId: 'a-veil-classic-brand',
    isPopular: true,
    isAvailable: true,
    bookedDates: [daysFromNow(6), daysFromNow(7)],
    createdAt: '2026-07-08T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.8,
    reviewCount: 53,
  },
  {
    id: 'a-veil-short',
    slug: 'veil-short',
    sku: 'AC-002',
    kind: 'accessory',
    categoryId: 'veils',
    subcategoryId: 'veils-short',
    accessoryType: 'veil',
    tags: ['фата', 'кружево'],
    name: 'Фата короткая с кружевом',
    description: 'Короткая фата до плеч с кружевной каймой. Подходит к платьям с открытой спиной.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 120_000,
    salePrice: 420_000,
    deposit: 80_000,
    currency: 'UZS',
    material: 'Фатин, кружево',
    oneSize: true,
    variants: seedVariants('a-veil-short', 'veil-short-ivory', 2),
    defaultVariantId: 'a-veil-short-brand',
    isNew: true,
    isAvailable: true,
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.6,
    reviewCount: 18,
  },
  {
    id: 'a-tiara-crystal',
    slug: 'tiara-crystal',
    sku: 'AC-003',
    kind: 'accessory',
    categoryId: 'jewelry',
    subcategoryId: 'jewelry-tiara',
    accessoryType: 'tiara',
    tags: ['диадема', 'кристаллы'],
    name: 'Диадема «Кристалл»',
    description: 'Серебристая диадема с австрийскими кристаллами. Гибкая основа — не давит.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 150_000,
    salePrice: 780_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Сплав, кристаллы',
    oneSize: true,
    variants: seedVariants('a-tiara-crystal', 'tiara-crystal-silver', 2),
    defaultVariantId: 'a-tiara-crystal-brand',
    isFeatured: true,
    isPopular: true,
    isAvailable: true,
    bookedDates: [daysFromNow(4), daysFromNow(5)],
    createdAt: '2026-07-20T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.9,
    reviewCount: 34,
  },
  {
    id: 'a-tiara-grand',
    slug: 'tiara-grand',
    sku: 'AC-004',
    kind: 'accessory',
    categoryId: 'jewelry',
    subcategoryId: 'jewelry-tiara',
    accessoryType: 'tiara',
    tags: ['диадема', 'премиум'],
    name: 'Диадема «Тиара Гранд»',
    description: 'Высокая объёмная диадема для пышных причёсок. Эффектно смотрится на фото.',
    offerTypes: ['rent'],
    rentPrice: 250_000,
    deposit: 300_000,
    currency: 'UZS',
    material: 'Сплав, жемчуг, кристаллы',
    oneSize: true,
    variants: seedVariants('a-tiara-grand', 'tiara-grand-silver', 2),
    defaultVariantId: 'a-tiara-grand-brand',
    isNew: true,
    isAvailable: true,
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.7,
    reviewCount: 11,
  },
  {
    id: 'a-earrings-dew',
    slug: 'earrings-dew',
    sku: 'AC-005',
    kind: 'accessory',
    categoryId: 'jewelry',
    subcategoryId: 'jewelry-earrings',
    accessoryType: 'jewelry',
    tags: ['серьги', 'жемчуг'],
    name: 'Серьги «Роса»',
    description: 'Длинные серьги с каплями из жемчуга. Лёгкие — не тянут мочку.',
    offerTypes: ['sale'],
    salePrice: 320_000,
    oldPrice: 450_000,
    currency: 'UZS',
    material: 'Серебро 925, жемчуг',
    oneSize: true,
    variants: seedVariants('a-earrings-dew', 'earrings-dew', 2),
    defaultVariantId: 'a-earrings-dew-brand',
    isAvailable: true,
    createdAt: '2026-06-10T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.5,
    reviewCount: 22,
  },
  {
    id: 'a-necklace-lace',
    slug: 'necklace-lace',
    sku: 'AC-006',
    kind: 'accessory',
    categoryId: 'jewelry',
    subcategoryId: 'jewelry-earrings',
    accessoryType: 'jewelry',
    tags: ['колье', 'ажур'],
    name: 'Колье «Ажур»',
    description: 'Тонкое ажурное колье под платья с открытым верхом.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 90_000,
    salePrice: 380_000,
    deposit: 120_000,
    currency: 'UZS',
    material: 'Сплав, фианиты',
    oneSize: true,
    variants: seedVariants('a-necklace-lace', 'necklace-lace', 2),
    defaultVariantId: 'a-necklace-lace-brand',
    isAvailable: true,
    createdAt: '2026-06-24T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.4,
    reviewCount: 8,
  },
  {
    id: 'a-belt-pearl',
    slug: 'belt-pearl',
    sku: 'AC-007',
    kind: 'accessory',
    categoryId: 'jewelry',
    subcategoryId: 'jewelry-belt',
    accessoryType: 'belt',
    tags: ['пояс', 'жемчуг'],
    name: 'Пояс «Жемчуг»',
    description: 'Расшитый пояс на завязках — меняет силуэт простого платья.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 110_000,
    salePrice: 490_000,
    deposit: 100_000,
    currency: 'UZS',
    material: 'Атласная лента, бисер',
    oneSize: true,
    variants: seedVariants('a-belt-pearl', 'belt-pearl', 2),
    defaultVariantId: 'a-belt-pearl-brand',
    isAvailable: true,
    createdAt: '2026-07-08T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.3,
    reviewCount: 15,
  },
  {
    id: 'a-gloves-satin',
    slug: 'gloves-satin',
    sku: 'AC-008',
    kind: 'accessory',
    categoryId: 'extras',
    subcategoryId: 'extras-gloves',
    accessoryType: 'gloves',
    tags: ['перчатки', 'атлас'],
    name: 'Перчатки атласные длинные',
    description: 'Длинные перчатки выше локтя. Классический аксессуар для вечернего образа.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 80_000,
    salePrice: 260_000,
    deposit: 60_000,
    currency: 'UZS',
    material: 'Атлас',
    sizeLabels: ['S', 'M', 'L'],
    variants: seedVariants('a-gloves-satin', 'gloves-satin-white', 2),
    defaultVariantId: 'a-gloves-satin-brand',
    isAvailable: true,
    createdAt: '2026-06-24T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.2,
    reviewCount: 13,
  },
  {
    id: 'a-bolero-lace',
    slug: 'bolero-lace',
    sku: 'AC-009',
    kind: 'accessory',
    categoryId: 'veils',
    subcategoryId: 'veils-bolero',
    accessoryType: 'bolero',
    tags: ['болеро', 'кружево'],
    name: 'Болеро кружевное',
    description: 'Кружевное болеро с длинным рукавом — закрывает плечи во время церемонии.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 190_000,
    salePrice: 720_000,
    deposit: 150_000,
    currency: 'UZS',
    material: 'Кружево',
    sizeLabels: ['42-44', '46-48', '50-52'],
    variants: seedVariants('a-bolero-lace', 'bolero-lace', 2),
    defaultVariantId: 'a-bolero-lace-brand',
    isAvailable: true,
    bookedDates: [daysFromNow(9)],
    createdAt: '2026-07-20T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.6,
    reviewCount: 17,
  },
  {
    id: 'a-underskirt-3',
    slug: 'underskirt-3-rings',
    sku: 'AC-010',
    kind: 'accessory',
    categoryId: 'extras',
    subcategoryId: 'extras-underskirt',
    accessoryType: 'underskirt',
    tags: ['подъюбник', 'объём'],
    name: 'Подъюбник 3 кольца',
    description: 'Придаёт объём пышной юбке. Кольца съёмные — можно регулировать силуэт.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 130_000,
    salePrice: 450_000,
    deposit: 80_000,
    currency: 'UZS',
    material: 'Фатин, металлические кольца',
    sizeLabels: ['S/M', 'L/XL'],
    variants: seedVariants('a-underskirt-3', 'underskirt-3', 2),
    defaultVariantId: 'a-underskirt-3-brand',
    isAvailable: true,
    createdAt: '2026-06-10T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.4,
    reviewCount: 29,
  },
  {
    id: 'a-shoes-ivory',
    slug: 'shoes-ivory',
    sku: 'AC-011',
    kind: 'accessory',
    categoryId: 'shoes',
    accessoryType: 'shoes',
    tags: ['туфли', 'каблук'],
    name: 'Туфли «Айвори»',
    description: 'Туфли на устойчивом каблуке 7 см с мягкой стелькой — выдержат весь день.',
    offerTypes: ['sale'],
    salePrice: 890_000,
    oldPrice: 1_150_000,
    currency: 'UZS',
    material: 'Эко-кожа, атлас',
    sizeLabels: ['36', '37', '38', '39', '40'],
    variants: seedVariants('a-shoes-ivory', 'shoes-ivory', 2),
    defaultVariantId: 'a-shoes-ivory-brand',
    isPopular: true,
    isAvailable: true,
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: 'a-cape-train',
    slug: 'cape-train',
    sku: 'AC-012',
    kind: 'accessory',
    categoryId: 'veils',
    subcategoryId: 'veils-bolero',
    accessoryType: 'veil',
    tags: ['накидка', 'шлейф'],
    name: 'Накидка-шлейф',
    description:
      'Съёмная накидка со шлейфом — превращает прямое платье в торжественное за секунду.',
    offerTypes: ['rent'],
    rentPrice: 220_000,
    deposit: 200_000,
    currency: 'UZS',
    material: 'Органза',
    oneSize: true,
    variants: seedVariants('a-cape-train', 'cape-train', 3),
    defaultVariantId: 'a-cape-train-brand',
    isNew: true,
    isFeatured: true,
    isAvailable: true,
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.8,
    reviewCount: 7,
  },
];
