import type { Dress } from './helper.types.catalog';
import { daysFromNow, sizes, variant } from './mockdata.helpers';

const NOW = '2026-01-15T10:00:00.000Z';

export const MOCK_DRESSES: Dress[] = [
  {
    id: 'd-aurora',
    slug: 'aurora',
    sku: 'WD-001',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-princess',
    tags: ['шлейф', 'корсет', 'блеск'],
    name: 'Аврора',
    description:
      'Пышное платье с многослойной юбкой из фатина и расшитым корсетом. Длинный шлейф отстёгивается — удобно для танцев.',
    careInstructions: 'Только сухая химчистка. Хранить в чехле, не складывать корсет.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 2_800_000,
    salePrice: 9_500_000,
    deposit: 1_500_000,
    oldPrice: 3_400_000,
    currency: 'UZS',
    silhouette: 'princess',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['tulle', 'satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([40, 42, 44, 46], [48]),
    trainLength: 180,
    hasCorset: true,
    collectionYear: 2026,
    variants: [
      variant('d-aurora-ivory', 'Айвори', '#F5EFE6', 'aurora-ivory'),
      variant('d-aurora-white', 'Белый', '#FFFFFF', 'aurora-white'),
    ],
    defaultVariantId: 'd-aurora-ivory',
    isNew: true,
    isFeatured: true,
    isPopular: true,
    isAvailable: true,
    bookedDates: [daysFromNow(6), daysFromNow(7), daysFromNow(20), daysFromNow(21)],
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'd-bella',
    slug: 'bella',
    sku: 'WD-002',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-mermaid',
    tags: ['кружево', 'облегающее'],
    name: 'Белла',
    description:
      'Силуэт «русалка» из французского кружева. Подчёркивает фигуру, юбка расширяется от колена.',
    careInstructions: 'Сухая химчистка. Беречь кружево от зацепок.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 2_200_000,
    salePrice: 7_800_000,
    deposit: 1_200_000,
    currency: 'UZS',
    silhouette: 'mermaid',
    neckline: 'v-neck',
    sleeve: 'transparent',
    fabrics: ['lace', 'crepe'],
    shade: 'champagne',
    sizes: sizes([40, 42, 44], [46, 48]),
    trainLength: 120,
    hasCorset: false,
    collectionYear: 2026,
    variants: [
      variant('d-bella-champagne', 'Шампань', '#E8D9C0', 'bella-champagne'),
      variant('d-bella-ivory', 'Айвори', '#F5EFE6', 'bella-ivory'),
    ],
    defaultVariantId: 'd-bella-champagne',
    isNew: true,
    isPopular: true,
    isAvailable: true,
    bookedDates: [daysFromNow(3), daysFromNow(12), daysFromNow(13)],
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.8,
    reviewCount: 31,
  },
  {
    id: 'd-victoria',
    slug: 'victoria',
    sku: 'WD-003',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-a-line',
    tags: ['атлас', 'классика'],
    name: 'Виктория',
    description:
      'Классический А-силуэт из плотного атласа. Универсальный вариант — подходит для любого типа фигуры.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_900_000,
    salePrice: 6_400_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'boat',
    sleeve: 'none',
    fabrics: ['satin'],
    shade: 'white',
    sizes: sizes([42, 44, 46, 48, 50]),
    trainLength: 90,
    hasCorset: true,
    isMaternityFriendly: true,
    collectionYear: 2025,
    variants: [
      variant('d-victoria-white', 'Белый', '#FFFFFF', 'victoria-white'),
      variant('d-victoria-blush', 'Пудровый', '#E8C8C8', 'victoria-blush'),
      variant('d-victoria-ivory', 'Айвори', '#F5EFE6', 'victoria-ivory'),
    ],
    defaultVariantId: 'd-victoria-white',
    isFeatured: true,
    isAvailable: true,
    bookedDates: [daysFromNow(9)],
    createdAt: '2026-07-01T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.7,
    reviewCount: 58,
  },
  {
    id: 'd-gracia',
    slug: 'gracia',
    sku: 'WD-004',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-straight',
    tags: ['минимализм', 'креп'],
    name: 'Грация',
    description:
      'Прямое платье в стиле минимализм. Без декора — акцент на крой и качество ткани.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 1_500_000,
    salePrice: 5_200_000,
    deposit: 800_000,
    currency: 'UZS',
    silhouette: 'straight',
    neckline: 'halter',
    sleeve: 'none',
    fabrics: ['crepe'],
    shade: 'ivory',
    sizes: sizes([40, 42, 44, 46]),
    hasCorset: false,
    collectionYear: 2026,
    variants: [variant('d-gracia-ivory', 'Айвори', '#F5EFE6', 'gracia-ivory')],
    defaultVariantId: 'd-gracia-ivory',
    isNew: true,
    isAvailable: true,
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.6,
    reviewCount: 12,
  },
  {
    id: 'd-dolce',
    slug: 'dolce',
    sku: 'WD-005',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-princess',
    tags: ['премиум', 'вышивка', 'шлейф'],
    name: 'Дольче',
    description:
      'Премиум-модель ручной вышивки: бисер, пайетки и объёмные цветы на корсете. Шлейф 2,5 метра.',
    careInstructions: 'Только сухая химчистка у мастера по свадебным платьям.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 3_500_000,
    salePrice: 12_000_000,
    deposit: 2_000_000,
    currency: 'UZS',
    silhouette: 'princess',
    neckline: 'off-shoulder',
    sleeve: 'long',
    fabrics: ['tulle', 'lace', 'organza'],
    shade: 'ivory',
    sizes: sizes([42, 44], [40, 46]),
    trainLength: 250,
    hasCorset: true,
    collectionYear: 2026,
    variants: [variant('d-dolce-ivory', 'Айвори', '#F5EFE6', 'dolce-ivory', 4)],
    defaultVariantId: 'd-dolce-ivory',
    isFeatured: true,
    isPopular: true,
    isAvailable: true,
    bookedDates: [daysFromNow(4), daysFromNow(5), daysFromNow(18), daysFromNow(25)],
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: NOW,
    rating: 5,
    reviewCount: 19,
  },
  {
    id: 'd-eliza',
    slug: 'eliza',
    sku: 'WD-006',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-a-line',
    tags: ['рукава', 'скромное'],
    name: 'Элиза',
    description:
      'А-силуэт с длинными прозрачными рукавами и закрытой спинкой. Хорошо смотрится на зимней свадьбе.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 2_000_000,
    salePrice: 6_900_000,
    deposit: 1_000_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'long',
    fabrics: ['lace', 'chiffon'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48]),
    trainLength: 100,
    isMaternityFriendly: true,
    collectionYear: 2025,
    variants: [
      variant('d-eliza-ivory', 'Айвори', '#F5EFE6', 'eliza-ivory'),
      variant('d-eliza-beige', 'Бежевый', '#E4D5C3', 'eliza-beige'),
    ],
    defaultVariantId: 'd-eliza-ivory',
    isAvailable: true,
    bookedDates: [daysFromNow(15)],
    createdAt: '2026-07-01T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.5,
    reviewCount: 24,
  },
  {
    id: 'd-jasmine',
    slug: 'jasmine',
    sku: 'WD-007',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-mermaid',
    tags: ['шампань', 'блеск'],
    name: 'Жасмин',
    description: 'Русалка цвета шампань с расшитым верхом и юбкой из мерцающей органзы.',
    offerTypes: ['rent'],
    rentPrice: 2_400_000,
    deposit: 1_200_000,
    currency: 'UZS',
    silhouette: 'mermaid',
    neckline: 'sweetheart',
    sleeve: 'strap',
    fabrics: ['organza', 'satin'],
    shade: 'champagne',
    sizes: sizes([40, 42, 44]),
    trainLength: 140,
    hasCorset: true,
    collectionYear: 2026,
    variants: [variant('d-jasmine-champagne', 'Шампань', '#E8D9C0', 'jasmine-champagne')],
    defaultVariantId: 'd-jasmine-champagne',
    isNew: true,
    isAvailable: true,
    bookedDates: [daysFromNow(2), daysFromNow(10), daysFromNow(11)],
    createdAt: '2026-07-28T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.8,
    reviewCount: 16,
  },
  {
    id: 'd-isabel',
    slug: 'isabel',
    sku: 'WD-008',
    kind: 'dress',
    categoryId: 'engagement',
    tags: ['роспись', 'короткое'],
    name: 'Изабель',
    description:
      'Короткое платье для росписи или помолвки. Лёгкое, не сковывает движения.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 900_000,
    salePrice: 3_200_000,
    deposit: 500_000,
    oldPrice: 1_200_000,
    currency: 'UZS',
    silhouette: 'short',
    neckline: 'v-neck',
    sleeve: 'short',
    fabrics: ['crepe', 'lace'],
    shade: 'white',
    sizes: sizes([40, 42, 44, 46]),
    collectionYear: 2026,
    variants: [
      variant('d-isabel-white', 'Белый', '#FFFFFF', 'isabel-white'),
      variant('d-isabel-blush', 'Пудровый', '#E8C8C8', 'isabel-blush'),
    ],
    defaultVariantId: 'd-isabel-white',
    isPopular: true,
    isAvailable: true,
    createdAt: '2026-07-15T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.4,
    reviewCount: 37,
  },
  {
    id: 'd-camellia',
    slug: 'camellia',
    sku: 'WD-009',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-princess',
    tags: ['фатин', 'объём'],
    name: 'Камелия',
    description: 'Максимально пышная юбка — семь слоёв фатина. Идеально для классической свадьбы.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 2_600_000,
    salePrice: 8_400_000,
    deposit: 1_300_000,
    currency: 'UZS',
    silhouette: 'princess',
    neckline: 'sweetheart',
    sleeve: 'none',
    fabrics: ['tulle', 'satin'],
    shade: 'white',
    sizes: sizes([42, 44, 46], [48, 50]),
    trainLength: 160,
    hasCorset: true,
    collectionYear: 2025,
    variants: [
      variant('d-camellia-white', 'Белый', '#FFFFFF', 'camellia-white'),
      variant('d-camellia-ivory', 'Айвори', '#F5EFE6', 'camellia-ivory'),
    ],
    defaultVariantId: 'd-camellia-white',
    isAvailable: true,
    bookedDates: [daysFromNow(8), daysFromNow(22)],
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.7,
    reviewCount: 45,
  },
  {
    id: 'd-laura',
    slug: 'laura',
    sku: 'WD-010',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-straight',
    tags: ['лаконичное', 'на второй день'],
    name: 'Лаура',
    description: 'Прямое платье без шлейфа — удобный вариант для выездной церемонии.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 1_300_000,
    salePrice: 4_600_000,
    deposit: 700_000,
    currency: 'UZS',
    silhouette: 'straight',
    neckline: 'boat',
    sleeve: 'strap',
    fabrics: ['crepe', 'chiffon'],
    shade: 'ivory',
    sizes: sizes([42, 44, 46, 48, 50]),
    isMaternityFriendly: true,
    collectionYear: 2025,
    variants: [variant('d-laura-ivory', 'Айвори', '#F5EFE6', 'laura-ivory')],
    defaultVariantId: 'd-laura-ivory',
    isAvailable: true,
    createdAt: '2026-06-02T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.3,
    reviewCount: 21,
  },
  {
    id: 'd-milana',
    slug: 'milana',
    sku: 'EV-001',
    kind: 'dress',
    categoryId: 'evening',
    subcategoryId: 'evening-long',
    tags: ['вечернее', 'бархат'],
    name: 'Милана',
    description: 'Длинное вечернее платье из бархата с разрезом. Для мамы невесты или подружки.',
    offerTypes: ['rent', 'sale'],
    rentPrice: 1_100_000,
    salePrice: 3_900_000,
    deposit: 600_000,
    currency: 'UZS',
    silhouette: 'straight',
    neckline: 'v-neck',
    sleeve: 'long',
    fabrics: ['velvet'],
    shade: 'pastel',
    sizes: sizes([42, 44, 46, 48, 50, 52]),
    collectionYear: 2026,
    variants: [
      variant('d-milana-emerald', 'Изумруд', '#3C6E63', 'milana-emerald'),
      variant('d-milana-burgundy', 'Марсала', '#7B3B47', 'milana-burgundy'),
    ],
    defaultVariantId: 'd-milana-emerald',
    isNew: true,
    isAvailable: true,
    createdAt: '2026-07-28T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.6,
    reviewCount: 14,
  },
  {
    id: 'd-nora',
    slug: 'nora',
    sku: 'EV-002',
    kind: 'dress',
    categoryId: 'evening',
    subcategoryId: 'evening-cocktail',
    tags: ['коктейльное', 'вечеринка'],
    name: 'Нора',
    description: 'Коктейльное платье до колена с пайетками. Для девичника и вечеринки.',
    offerTypes: ['rent'],
    rentPrice: 700_000,
    deposit: 400_000,
    currency: 'UZS',
    silhouette: 'short',
    neckline: 'halter',
    sleeve: 'none',
    fabrics: ['satin'],
    shade: 'pastel',
    sizes: sizes([40, 42, 44, 46]),
    collectionYear: 2026,
    variants: [
      variant('d-nora-silver', 'Серебро', '#C9C4BC', 'nora-silver'),
      variant('d-nora-gold', 'Золото', '#C9A227', 'nora-gold'),
    ],
    defaultVariantId: 'd-nora-silver',
    isAvailable: true,
    createdAt: '2026-07-15T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.2,
    reviewCount: 9,
  },
  {
    id: 'd-olivia',
    slug: 'olivia',
    sku: 'EN-001',
    kind: 'dress',
    categoryId: 'engagement',
    tags: ['помолвка', 'пудровый'],
    name: 'Оливия',
    description:
      'Нежное платье пудрового оттенка для помолвки. А-силуэт с поясом из атласа.',
    offerTypes: ['rent', 'sale', 'tailoring'],
    rentPrice: 1_000_000,
    salePrice: 3_500_000,
    deposit: 500_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'sweetheart',
    sleeve: 'strap',
    fabrics: ['chiffon', 'satin'],
    shade: 'blush',
    sizes: sizes([40, 42, 44, 46, 48]),
    isMaternityFriendly: true,
    collectionYear: 2026,
    variants: [
      variant('d-olivia-blush', 'Пудровый', '#E8C8C8', 'olivia-blush'),
      variant('d-olivia-beige', 'Бежевый', '#E4D5C3', 'olivia-beige'),
    ],
    defaultVariantId: 'd-olivia-blush',
    isNew: true,
    isPopular: true,
    isAvailable: true,
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.9,
    reviewCount: 27,
  },
  {
    id: 'd-patricia',
    slug: 'patricia',
    sku: 'WD-011',
    kind: 'dress',
    categoryId: 'wedding',
    subcategoryId: 'wedding-a-line',
    tags: ['архив', 'распродажа'],
    name: 'Патрисия',
    description: 'Модель прошлой коллекции. Продаётся со склада — состояние отличное.',
    offerTypes: ['sale'],
    salePrice: 2_800_000,
    oldPrice: 5_600_000,
    currency: 'UZS',
    silhouette: 'a-line',
    neckline: 'closed',
    sleeve: 'short',
    fabrics: ['satin', 'lace'],
    shade: 'ivory',
    sizes: sizes([44], [40, 42, 46]),
    collectionYear: 2023,
    variants: [variant('d-patricia-ivory', 'Айвори', '#F5EFE6', 'patricia-ivory', 2)],
    defaultVariantId: 'd-patricia-ivory',
    isAvailable: true,
    createdAt: '2026-06-02T10:00:00.000Z',
    updatedAt: NOW,
    rating: 4.1,
    reviewCount: 6,
  },
];
